* Prototype fund application

[[https://prototypefund.de/][website]]
[[https://prototypefund.de/faq/][FAQ]]
[[https://prototypefund.de/jury/][jury]]
[[https://secure.pt-dlr.de/pt-conference/conference/PrototypeFund6][Submission link]]

** An welchen Open-Source-Projekten hast Du/habt Ihr bisher gearbeitet [3max]?

[[https://github.com/beakerbrowser][Beaker browser]]

[[https://github.com/datproject][Dat protocol]]

[[https://internethealthreport.org/2018/][Mozilla Internet Health Report]]

[[https://github.com/MicheleNuijten/statcheck/][statcheck]]

[[https://github.com/CenterForOpenScience/osfr][osfr]]

[[https://github.com/mozilla/leadership-training][Mozilla Open Leadership Training]]

[[https://github.com/tomroy/mdtable2csv][mdtable2csv]]

** Bewerbt Ihr Euch als Team um die Förderung?

Chris Hubertus Joseph Hartgerink (Rufname: Chris)

** Projekttitel

Liberate Science

** Ordne das Projekt einem Bereich zu.

- [ ] Civic Tech
- [ ] Datensicherheit
- [ ] Data Literacy
- [x] Infrastruktur 

** Bezieht sich Dein Projekt auf den [[https://prototypefund.de/faq/][Themenschwerpunkt]] der 6. Runde?*

- [x] ja
- [ ] nein

** Beschreibe Dein Projekt kurz (700 zeichen)

Liberate Science baut mit dem p2p-Protokoll Dat eine dezentrale
Wissensinfrastruktur auf.

Hier wird die Forschung fortlaufend kommuniziert, ist ohne Paywalls
und geht auf Fragen der Reproduzierbarkeit und Replikation ein, indem
die Offenheit der durchgeführten Forschung verändert wird.

Die Forscher*innen kommunizieren jeden Schritt des Forschungsprozesses
(Theorie, Vorhersagen, Design, Daten, Code usw.) mit direkten Links zu
den vorhergehenden Schritten. Diese Links bieten eine bessere
Herkunftsgeschichte von Befunden als jetzt in retrospektiven
Veröffentlichungen. Dadurch wird auch ein Wissensnetzwerk aufgebaut,
mit dem Forschung entdeckt, bewertet und geplant werden kann.

** Welches gesellschaftliche Problem willst Du mit Deinem Projekt lösen? (700 zeichen)

Probleme der Reproduzierbarkeit führen dazu, dass viele
Forschungsgelder verschwendet werden. In Anbetracht der Tatsache, dass
sich die Menschheit in (schweren) Krisen befindet, ist dies ein
Grundproblem, das den Fortschritt behindert.

Ursachen für Forschungsabfälle entstehen im Veröffentlichungsprozess,
der die Innovativität fördert über Strenge, und Datenfolterung oder
voreingenommener Veröffentlichung verursacht. Die Veröffentlichung
dauert Jahre und die finanzierten Ergebnisse sind nicht
zugänglich. Nicht-Text-Informationen (z. B. Code, Daten) werden nicht
effektiv kommuniziert.

Dies verhindert, dass Menschen ihr Wissen uneingeschränktes entdecken
und produzieren können.

** Wie willst Du Dein Projekt technisch umsetzen? (1300 zeichen)

Das Projekt hat drei interagierende Elemente: API; CLI; GUI. Die API
formt die Grundlage von CLI/GUI, das ermöglicht, dass andere Projekten
in der Zukunft auch ihre eigene CLI/GUI machen können um auf die
gleichen wissenschaftlichen Informationen zuzugreifen.

Die API wird geschrieben in NodeJS. Mit dem Standardmodul dat-node von
das Dat Project werden die Basisfunktionen implementiert, z. B.:
+ Profil/Wissenschaftliche Module ersetzen
+ Wissenschaftliche Module registrieren
+ registrierte Modulen verifizieren
+ Netzwerk von Modulen aufbauen (Daten)
+ rehosting von spezifische Versionen von Modulen

CLI vereinfacht es für Wissenschaftlern, diese neue Infrastruktur zu
nutzen. Das Format der CLI ist dabei vergleichbar mit Git
(z. B. `libscie ACTION TYPE ARGS`). CLI wird als NPM Modul
implementiert und von den Wissenschaftlern in der Praxis getestet.

Die GUI wird in Elektron mit Vue.js gebaut. Hier wird eine intuitive
Erfahrung aufgebaut, basierend auf den Prinzipien des Material
Design. Die GUI wird auch mit Wissenschaftlern getestet, um so eine
praktische Erfahrung zu entwickeln.

** Welche ähnlichen Lösungen gibt es schon, und was wird Dein Projekt anders bzw. besser machen? (400 zeichen)

Ähnliche Plattformen, wo wissenschaftliche Studien kommuniziert werden
wenn Wissenschaftler es wünschen, sind Open Science Framework
(https://osf.io), Artifacts.ai (https://artifacts.ai). Diese
zentralisieren die Daten und entscheiden teilweise, wie das Format
wird. Dies bildet eine Unterstützung für das jetzige "after-the-fact"
System. Allerdings bietet dies keine gründliche Alternative.

** Wer ist die Zielgruppe und wie soll Dein Tool sie erreichen?* (700 zeichen)

Die Zielgruppe sind Early Career Researchers (ECRs), weil Sie oft die
Problemen in die Wissenschaft erkennen, die Motivierung haben ihr
Forschungsverhalten zu ändern, und nicht verstehen wieso anno 2019
Forschungskommunikation noch immer so fundamental analog ist.

Ich bin selber eine Early Career Researcher und hab so ein Netzwerk
von Kollegen über die ganze Welt die ich anschreiben kann. Auch hab
ich letztes Jahr eine Fellowship bei Mozilla gemacht, die mich
unterstützt Leuten zu erreichen. Dabei geh ich noch immer auf
Konferenzen, wo ich das Projekt auch vortragen kann. Somit gibt es
viele Optionen um die ersten Nutzer*innen zu finden.

** Hast Du schon an der Idee gearbeitet? Wenn ja, beschreibe kurz den aktuellen Stand und erkläre die Neuerung. (700 zeichen)

Ja.

In den letzten zwei Jahren habe ich im Rahmen meiner Doktorarbeit das
Infrastrukturdesign recherchiert, um verschiedene Problemen der
Wissenschaft in eine konsistente und praktikable Lösung
umzuwandeln. Die Forschung ist basiert auf wissenschaftlichen Studien
in meta-research und der Iteration des ersten Entwurfs mit feedback
von Wissenschaftlern.

Das Projekt ist jetzt das Umsetzens des Entwurfes. Den Entwurf habe
ich letzten August finalisiert und danach habe ich eine Zeitlang frei
genommen weil ich durch meinen alten Job überarbeitet war. Jetzt fange
ich mit das Umsetzen von das Idee in eine Realität an und suche Geld
damit ich auch essen kann wenn ich daran arbeitet :)


** Link zum bestehenden Projekt (falls vorhanden)

https://chartgerink.github.io/2018dat-com

** Wie viele Stunden willst Du (bzw. will das Team) in den 6 Monaten Förderzeitraum an der Umsetzung arbeiten?*

Ich kann Vollzeit arbeiten an dem Projekt für die 6 Monate
(01.09.2019-31.01.2020). Somit sind es mindestens 6*4*40=960 Stunden.

** Skizziere kurz die wichtigsten Meilensteine, die Du (bzw. das Team) im Förderzeitraum umsetzen willst.

+ Basisfunktionen modulaire Forschungskommunikation implementieren in API     
+ CLI auf API bauen
+ Testrunde CLI mit Wissenschaftler (ein von jedem Kontinent)     
+ GUI Prototype (basic, kein weiteres design)     
+ Testrunde GUI mit Wissenschaftler (wieder ein von jedem Kontinent)     
+ GUI v1.0 (mit design)     

** Wenn meine Projektidee nicht gefördert wird, darf sie trotzdem auf prototypefund.de und in wissenschaftlichen Publikationen rund um das Programm veröffentlicht werden?*

- [x] ja
- [ ] nein
