* Shuttleworth Fellowship
  DEADLINE: <2019-06-01 Sat>

/Notes/

- 1500 letters p/question
- Submit [[https://www.shuttleworthfoundation.org/apply/form/][here]]

** Application questions

*** Tell us about the world as you see it

/A description of the status quo and context in which you will be
working/

Society is running on fumes---literally and figuratively.

Literally, because we're allowing humanity's domination of nature run
rampant into catastrophic climate change.

Figuratively, because a few dominating the many is now so egregious
that the masses' mental health and resources are sapped away, leaving
barely enough to keep functioning let alone organize effectively for
emancipation.

Organizations with a singular mission act at the expense of the
externalities to that mission. A mission can be financial (e.g.,
profit maximization) or social (e.g., eradicating polio).

These missions are determined by the few at the expense of the
many.

When I finished my Mozilla Fellowship, I was overworked. I see my
friends struggle at the expense of a mission, each in their own way,
and they're the privileged bunch (lawyers, doctors, consultants,
researchers)!

These organisational structures are neither sustainable or
pleasurable. The circumstances of domination may differ, but the
effects are similar. It's only going to get worse if we do nothing
about it.

*** What change do you want to make in the world?

/A description of what you want to change about the status quo, in the
world, your personal vision for this area/

People face issues in their daily lives they cannot address alone, but
organizations do not stimulate people to act on their beliefs. 

I imagine a world where organizations have as a mission to stimulate
collectives to act on the issues they face.

In order to fundamentally break away from this dynamic where people
are subjected to missions, I am building an organization model with
the mission to provide stimulation and resources for people to act
on beliefs.

This organization fundamentally supports its members in emancipating
themselves, instead of coopting their freedoms by wage slavery.

By building the first worker cooperative with open principles in its
bylaws, we provide workers with more agency, energy, money, and time
to act on their beliefs. These actions are only limited by not
exacerbating negative externalities we know about (e.g., climate
crisis, tax avoidance).

Fundamental organisational changes are that workers:
+ all have one vote, electing who manages
+ 7 hour workdays
+ uniform base pay for members, variable pay to incentivize unwanted
  tasks
+ direct budgetary profit sharing

Workers benefit directly by being put center stage in shaping their
work environment; profits are shared, used to act on beliefs, and
proliferate the open worker coop model.

*** What do you believe has prevented this change to date?

/Describe the innovations or questions you would like to explore
during the fellowship year/

The next step of the worker cooperative is possible through recent
changes in productive forces.

The first coops stem from 1844, when the First Industrial Revolution
passed into the Second (i.e., changes in production). We are
passing from the Second to the Third Industrial Revolution (Rifkin).

What do these developments mean for organizing an effective worker
cooperative? Coops remain scarce and venture capital funding has
increased, which provide no breeding ground to investigate this
question.

The four pillars (profit sharing, democratic management, reduced
workweek, base- & variable pay) are a result of the changes in
productive forces and increased potential of digital support
mechanisms, which I'd like to explore in practical circumstances.

I am interested in openly documenting and evaluating benefits and
issues that arise from implementing a radically different organization
structure. Questions include
+ How does the status quo accomodate fundamentally different
  organisation structures?
+ How can the four pillars practically be implemented?
+ Is it easier/more difficult to find workers when implementing a
  different kind of work?
+ How do workers evaluate the four pillars?
+ How do workers utilize the resources the four pillars provide them?
+ How do experts evaluate this kind of organization structure as it
  progresses?
These questions and dialogue on these aspects will be a large part of
the fellowship, while at the same time implementing a business idea.

*** What are you going to do to get there?

/A description of what you actually plan to do during the year/

I am implementing “Liberate Science” as the first Open Worker
Cooperative (OWC), servicing public project management
infrastructure. I developed this to address acute issues in science
(e.g., selective publication, exclusivity).

Workers within this OWC can use the direct and full budgetary
profit-sharing to initiate replicants of the OWC for issues they see
and want to act on, once revenue streams are flowing. From those
replicants of the OCW, profits again are directly shared to its
members, which can be invested in issues those members want to act
upon in OWCs, and so on.

In months 1-6, contractors develop the Liberate Science infrastructure
and start testing with early career researchers. Simultaneously, the
legal (e.g., bylaws) and organizational (e.g., onboarding)
preparations for the cooperative will be implemented as part of the
fellowship.

End of month 6 the OWC is registered in Germany, with the four pillars
enshrined in the bylaws (profit sharing, democratic management,
reduced workweek, base- & variable pay). openworker.coop will be
launched with base resources to launch an OWC in Germany.

In months 7-12, practical OWC building initiates. This includes
several workers joining the coop and building a collective
culture. Contractors are phased out for worker-owners over these
months. I will be working on both gearing the first OWC towards
revenue and extending the legal framework for OWCs internationally.


*** What challenges or uncertainties do you expect to face?

This project advances the potential of a worker cooperative and
implements an idea that aims to reform scientific practice. It is very
ambitious and I am uncertain about pulling this off; it is however the
one thing I want to work on. I aim to build a community to tackle
these issues collectively.

Some of my uncertainties include:
+ A radically different organization structure requires radically
  rethinking many organization processes; I expect the daily work
  environment to be so different that it might be hard for people to
  adapt. Progress on the business idea may slow as a result. For
  example, onboarding into a worker cooperative culture is very
  different; how does that affect getting up to speed?
+ I expect that finding workers to join the coop might be difficult
  due to not understanding why things are done so
  differently. Onboarding creates its own issues, but that assumes
  there are people to onboard. I am afraid I have idealized this form
  of organizing and that it does not resonate in practice.
+ I am excited and uncertain about the challenge of creating bylaws
  for a worker coop. How to make these equitable, legally sound,
  inclusive, etc. seems like a major challenge that will require much
  planning and consultation. One major point is how to
  minimize/eliminate negative externalities.


*** What part does openness play in your idea?

Open is community to me and I feel like we can use more community in
our work environments (and daily lives). In that sense, open has been
key to inspiring the outlined vision in the first place.

Working open is central in everything I have done over the last seven
years. Nothing is done alone, hence, nothing should have results for a
few.

I think the values I outline for an Open Worker Cooperative shows
this: It puts the value produced by the many right back into the hands
of the many, distributing agency over the organization. 

All of this to stimulate community building and provide the
agency, money, energy, and time to act in crucial moments of humanity
given the runaway domination.

The importance of community comes from a deep gratitude for what the
open community has meant to me over the years. We all struggle from
issue to issue, feeling like we cannot have a meaningful impact. I
know how much mental energy that feeling drains; the community has
pulled me through and I hope to do contribute to this collective
effort in this way.

I am committed to serving progress in line with the open principles
and any project I undertake needs to do so too, making openness a
tenet in my life. The fellowship helps change timeframes and scale of
my work, not its dedication.

*** Project name

Open Worker Coop
