* Prototype fund application

[[https://prototypefund.de/][website]]
[[https://prototypefund.de/faq/][FAQ]]
[[https://prototypefund.de/jury/][jury]]
[[https://secure.pt-dlr.de/pt-conference/conference/PrototypeFund6][Submission link]]

** An welchen Open-Source-Projekten hast Du/habt Ihr bisher gearbeitet [3max]?

[[https://github.com/beakerbrowser][Beaker browser]]

[[https://github.com/datproject][Dat protocol]]

[[https://internethealthreport.org/2018/][Mozilla Internet Health Report]]

[[https://github.com/MicheleNuijten/statcheck/][statcheck]]

[[https://github.com/CenterForOpenScience/osfr][osfr]]

[[https://github.com/mozilla/leadership-training][Mozilla Open Leadership Training]]

[[https://github.com/tomroy/mdtable2csv][mdtable2csv]]

** Bewerbt Ihr Euch als Team um die Förderung?

Chris Hubertus Joseph Hartgerink (Rufname: Chris)

** Projekttitel

Liberate Science

** Ordne das Projekt einem Bereich zu.

- [ ] Civic Tech
- [ ] Datensicherheit
- [ ] Data Literacy
- [x] Infrastruktur 

** Bezieht sich Dein Projekt auf den [[https://prototypefund.de/faq/][Themenschwerpunkt]] der 6. Runde?*

- [x] ja
- [ ] nein

** Beschreibe Dein Projekt kurz (700 zeichen)

Wissenschaftliche Kommunikationsinfrastruktur bauen mit p2p protocol
Dat; komplette "after-the-fact" Publikationen umsetzen in teilweise
und chronologisch rapportierte "as-you-go" Modulen (zb. Theorie,
nächstes Vorhersagen, Design, Materialien, &c). Dies verbessert die
Erfüllung der fünf Funktionen des Wissenschaftlichen
Kommunikationssystems:

+ Entdeckung; alles immer gratis zugänglich
+ Bewertung; Module bauen Wissensnetwerk, erleichtert Netwerkbewertungen
+ Registrierung; weniger 'Publikationsbias' weil die erste
  Rapportierung vor dem Resultat passiert
+ Zertifizierung; empirische Zyklen eingebaut in Rapportierung
+ Archivierung; jeder hilft, alles langfristich zu speichern

** Welches gesellschaftliche Problem willst Du mit Deinem Projekt lösen? (700 zeichen)

Viel Forschungsgeld wird "weggeschmissen" durch schlechte Wissenschaft
(zb. Reproduzierbarkeitskrise). Das Zurückerhalt der Gelder für die
Forschungsgruppen und die Gesellschaft fällt niedriger aus, als sie
nötig ist. Mit den großen Krisen, die der Mensch lösen muss in
Zukunft, ist das ein "Wurzelproblem."

In der Kommunikation in der Wissenschaft gibt es viele
Probleme. Einige Ursache sind folgende: lange Dauer, Unzugänglichkeit,
selektive Publikation, textbasis statt eindrückliche Daten, Verzerrung
des emprischen Zyklus. Viele dieser Ursachen werden nur partiell
angezeigt, nicht in kombination aller Ursachen. Partielle Lösungen
sind auch unpraktisch um die Totalität zu ändern.

# Dieses Projekt löst die Problemen nicht nur in das System, aber auch
# die Weise woauf das entwickelt wird. Jetzt ist es nur das heutige
# System oder der Autobahn weil es alles Platform Systemen sind (mit
# lock-in, genau so wie Facebook oder Twitter). Ich stell vor
# Infrastruktur auf zu setzen, wo jedem eine andere Lösung auf bauen
# kann wenn es an ein Paar Basisprinzipen [sufficed]. 

** Wie willst Du Dein Projekt technisch umsetzen? (1300 zeichen)

Das Projekt kennt drei Elemente: API; CLI; GUI. Diese Interaktionen,
wo die API die Grundlage von CLI/GUI formt, womit andere Projekten
in der Zukunft auch ihre eigene CLI/GUI machen können für dieselbe
Wissenschaftliche Information.

API wird geschrieben in NodeJS. Mit dem Standardmodul [[https://github.com/datproject/dat-node][dat-node]] von
das Dat Project werden die Basisfunktionen implementiert, zb.:
+ Profil/Wissenschaftliche Module ersetzen
+ Wissenschaftliche Module registrieren 
+ registrierte Modulen verifizieren
+ Netzwerk von Modulen aufbauen (Daten)
+ rehosting von spezifische Versionen von Modulen

CLI vereinfacht es für Wissenschaftler, diese neue Infrastruktur zu
nutzen. Das Format der CLI ist dabei vergleichbar mit Git (zb `libscie
ACTION TYPE ARGS`). CLI wird in NPM modul implementiert und von den
Wissenschftern in der Praxis getestet.

GUI wird in Elektron mit Vue.js gebaut. Hier wird eine intuitive
Erfahrung aufgebaut, basierend auf die Material Design Prinzipen. GUI
wird auch mit Wissenschaftler getestet, um so eine praktische
Erfahrung zu entwicklen.

** Welche ähnlichen Lösungen gibt es schon, und was wird Dein Projekt anders bzw. besser machen? (400 zeichen)

Ähnliche Platforms, wo wissenschaftliche Studien kommuniziert worden
wenn Wissenschaftler dies wünschen sind [[https://osf.io][Open Science Framework]],
[[https://artifacts.ai][Artifacts]]. Diese zentralisieren die Daten und entscheiden teilweise,
wie das Format wird. Dies bildet eine Unterstützung für das jetztige
"after-the-fact" System. Allerdings bietet dies keine gründliche
Alternativ.

** Wer ist die Zielgruppe und wie soll Dein Tool sie erreichen?* (700 zeichen)

Die Zielgruppe sind Early Career Researchers (ECRs), weil Sie oft die
Problemen in die Wissenschaft erkennen, die Motivierung haben ihre
verhältnis zu ändern, und nicht verstehen wieso anno 2019
Forschungskommunikation noch immer so fundamentell Analog ist.

Ich bin selber eine Early Career Researcher und hab so ein Netzwerk
von Kollegen über die ganze Welt die ich anschreiben kann. Auch hab
ich letztes Jahr eine Fellowship bei Mozilla gemacht, die mir
unterstützen Leuten zu erreichen. Dabei, geh ich noch immer auf
Konferenzen, wo ich das Projekt auch vor kann tragen. So sind viele
Optionen um die Erste Braucher zu finden.

** Hast Du schon an der Idee gearbeitet? Wenn ja, beschreibe kurz den aktuellen Stand und erkläre die Neuerung. (700 zeichen)

Ja. 

Vor zwei Jahren hab ich das Algemeine Entwerp von der Infrastruktur
recherchiert als Teil von meine Promovierung, um verschiedene
Problemen in die Wissenschaft auf zu heben in eine konsistente und
brauchbare Lösung. Die Recherchierung ist basiert auf
Wissenschaftliche Studien und der Iterierung von das erste Entwerp mit
Wissenschäftler.

Das Projekt ist jetzt in die übersetzende Fase von das Entwerp in der
Programmatur. Das Algemeine Entwerp habe ich letzter August
finalisiert, und danach habe ich eine Zeit frei genommen weil ich
durch meine alter Job überarbeitet war. Jetzt fange ich mit die
Übersetzung an und suche Gelde das ich auch essen kann wenn ich daran
Arbeit :)

** Link zum bestehenden Projekt (falls vorhanden)

https://chartgerink.github.io/2018dat-com

** Wie viele Stunden willst Du (bzw. will das Team) in den 6 Monaten Förderzeitraum an der Umsetzung arbeiten?*

Ich kann Volzeit arbeiten an das Projekt für die 6 Monaten
(01.09.2019-31.01.2020). Sonst ist es mindestens 6*4*40=960 Stunde.

** Skizziere kurz die wichtigsten Meilensteine, die Du (bzw. das Team) im Förderzeitraum umsetzen willst.

+ Basisfunktionen modulaire Forschungskommunikation implementieren in API
+ API in CLI aufheben
+ Testrunde CLI mit Wissenschaftler (ein von jedem Kontinent)
+ GUI Prototype (basic, kein weitere design)
+ Testrunde GUI mit Wissenschaftler (wieder ein von jedem Kontinent)
+ GUI v1.0 (mit design)

** Wenn meine Projektidee nicht gefördert wird, darf sie trotzdem auf prototypefund.de und in wissenschaftlichen Publikationen rund um das Programm veröffentlicht werden?*

- [x] ja
- [ ] nein
